version: "3"
services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: enael/yuboclient
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
        stdin_open: true
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: enael/yuboserver
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app


